/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnixDomainSocket_UnixDomainSocketOutputStream */

#ifndef _Included_UnixDomainSocket_UnixDomainSocketOutputStream
#define _Included_UnixDomainSocket_UnixDomainSocketOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
