/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnixDomainSocket_UnixDomainSocketInputStream */

#ifndef _Included_UnixDomainSocket_UnixDomainSocketInputStream
#define _Included_UnixDomainSocket_UnixDomainSocketInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef UnixDomainSocket_UnixDomainSocketInputStream_MAX_SKIP_BUFFER_SIZE
#define UnixDomainSocket_UnixDomainSocketInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
