/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnixDomainSocket */

#ifndef _Included_UnixDomainSocket
#define _Included_UnixDomainSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UnixDomainSocket
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_UnixDomainSocket_nativeOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     UnixDomainSocket
 * Method:    nativeRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_UnixDomainSocket_nativeRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     UnixDomainSocket
 * Method:    nativeWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_UnixDomainSocket_nativeWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     UnixDomainSocket
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UnixDomainSocket_nativeClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     UnixDomainSocket
 * Method:    nativeCloseInput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UnixDomainSocket_nativeCloseInput
  (JNIEnv *, jclass, jint);

/*
 * Class:     UnixDomainSocket
 * Method:    nativeCloseOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_UnixDomainSocket_nativeCloseOutput
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
