/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnixDomainSocket_UnixDomainSocketReadThread */

#ifndef _Included_UnixDomainSocket_UnixDomainSocketReadThread
#define _Included_UnixDomainSocket_UnixDomainSocketReadThread
#ifdef __cplusplus
extern "C" {
#endif
#undef UnixDomainSocket_UnixDomainSocketReadThread_MIN_PRIORITY
#define UnixDomainSocket_UnixDomainSocketReadThread_MIN_PRIORITY 1L
#undef UnixDomainSocket_UnixDomainSocketReadThread_NORM_PRIORITY
#define UnixDomainSocket_UnixDomainSocketReadThread_NORM_PRIORITY 5L
#undef UnixDomainSocket_UnixDomainSocketReadThread_MAX_PRIORITY
#define UnixDomainSocket_UnixDomainSocketReadThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
